### ISSUE TITLE
Documentation is unsync with code

### ISSUE THREAD

**Issue by sokolovstas** [jivanpal/drat#22]
Hi!

I have cloned repo and find out that source code for version 1.x but documentation for 2.x
Tried to checkout branch and can't compile it

Any hints?

**Comment by jivanpal** [comment]
Hi, @sokolovstas, documentation has been drafted for v0.2, which is being developed. v0.1.3 has a slightly different set of commands, and notably no `search` or `create-index`. To see a list of commands, run `drat`, and to see what arguments a particular command takes, run it without any arguments, e.g. `drat explore-fs-tree` outputs:

```
Usage:   explore-fs-tree <container> <fs tree root node address> <omap tree root node address>
Example: explore-fs-tree /dev/disk0s2 0xd02a4 0x3af2
```

These old commands do not have support for any more complex object indirection/identification methods, such as inferring the FS root tree and omap tree from a volume name.

**Comment by sokolovstas** [comment]
Hi @jivanpal, is there any plans to publish second version? This tool is great, I have found and restore my private key from corrupted apfs driver but can't restore folder because it not listed in tree but exist when I run list raw. Just can't figure out how to use drat to restore folder.

**Comment by jivanpal** [comment]
Thanks, glad to know Drat has been of help to you! Yes, regular work on the next version (v0.2.0) is ongoing, I hope to release it in the next month or so. Unfortunately, as of v0.1.3, the `recover` and `recover-raw` commands can only recover individual files, but see #7 for some guidance on how to recover an entire directory. Recursive recover/undelete support (that is, recovery of entire directories) is slated for v0.2.0. If you're interested, you can see the project roadmap via the Projects tab here on GitHub.
