### ISSUE TITLE
How to change the Volume to /dev/disk7?

### ISSUE THREAD

**Issue by Massaguana** [jivanpal/drat#38]
Hello,

maybe an stupid question... but what are correct steps to change the Volume?

My Volume name is: /dev/disk7

Thank you

**Comment by jivanpal** [comment]
Hi, you don't just specify the volume, but rather the container (actual APFS partition) and the index of the volume within the container separately. Output of `diskutil list` and `diskutil apfs list` will be helpful to figure out the right parameters.
