### ISSUE TITLE
Handling of this case has not yet been implemented.

### ISSUE THREAD

**Issue by master0v** [jivanpal/drat#41]
...
- There are 10 checkpoint-mappings in this checkpoint.

Reading the Ephemeral objects used by this checkpoint ... OK.
Validating the Ephemeral objects ... FAILED.
An Ephemeral object used by this checkpoint is malformed. Going back to look at the previous checkpoint instead.
END: Handling of this case has not yet been implemented.

**Comment by jivanpal** [comment]
Hi, someone else emailed me recently wanting to explore a disk with bad Ephemerals, so I pushed a quick change to `ignore-ephemerals` branch for them. You can checkout that branch and compile to get around this for now.
